feat: start docker if not running
ExchangeUnion/xud-ui pull request #121
Opened 2020-11-30 14:36 UTC by erkarl

Closes https://github.com/ExchangeUnion/xud-ui/issues/74

2020-11-30 18:27 UTC, krrprr approved these changes

2020-12-01 11:51 UTC, raladev requested changes
- [ ] `const WINDOWS_DOCKER_EXECUTABLE_PATH = "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe";`
I m not sure that path hardcoding is good idea, user may have preinstalled docker with another path (any developer, for example) or just have another system disk letter (saw it once in my live :) ).

maybe is there a way to get legitimate path of docker without hardcoding?

2020-12-01 12:26 UTC, erkarl commented
>     * [ ]  `const WINDOWS_DOCKER_EXECUTABLE_PATH = "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe";`
>       I m not sure that path hardcoding is good idea, user may has preinstalled docker with another path (any developer, for example) or just another system disk letter (saw it once in my live :) ).
> 
> 
> maybe is there a way to get legitimate path of docker without hardcoding?

Not a straight forward thing to implement as it would be error prone. I'm assuming most users will have it installed to the default path. I propose we address this as a follow-up issue to harden the start docker process.

2020-12-01 14:18 UTC, raladev approved these changes

2020-12-01 14:18 UTC, merged