fix: add min width/height so it doesn't break the design
ExchangeUnion/xud-ui pull request #126
Opened 2020-12-08 12:19 UTC by scorebreaker

Closes #81

2020-12-08 17:12 UTC, raladev requested changes
Del

2020-12-08 17:18 UTC, raladev requested changes
window size lower then 900x600 breaks layout on certain pages.
minHeight may be reduced to 600, but there is no reason for this.

2020-12-08 17:18 UTC, raladev commented on public/electron.js
> +    minHeight: 150,
minHeight: 680

2020-12-08 17:18 UTC, raladev commented on public/electron.js
> +    minWidth: 600,
minWidth: 900

2020-12-08 18:16 UTC, krrprr requested changes
Let's set the min sizes same as the initial window size.
Otherwise looks good to me.

2020-12-09 09:32 UTC, krrprr approved these changes
Code-wise ACK, basic testing passed.
Thank you!

2020-12-09 10:49 UTC, raladev approved these changes

2020-12-09 10:50 UTC, merged