Feat/reopen hint
ExchangeUnion/xud-ui pull request #99
Opened 2020-11-09 19:06 UTC by krrprr

Closes https://github.com/ExchangeUnion/xud-ui/issues/76

Also changed `Reboot required to continue.` -> `System reboot required to continue.`

2020-11-09 19:09 UTC, erkarl approved these changes

2020-11-10 11:20 UTC, kilrau requested changes

2020-11-10 11:20 UTC, kilrau commented on src/setup/create/RestartRequired.tsx
> +          After reboot, open XUD Explorer.
```suggestion
          After reboot, please reopen XUD Explorer.
```

2020-11-10 11:24 UTC, kilrau approved these changes

2020-11-10 11:35 UTC, merged